"""visual allow_mirror

Revision ID: 7c32bf6f0219
Revises: a17fbbc73559
Create Date: 2026-09-13 22:43:06.493005
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7c32bf6f0219'
down_revision: str | Sequence[str] | None = 'a17fbbc73559'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_mirror', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.drop_column('allow_mirror')

    # ### end Alembic commands ###
