"""initial schema

Revision ID: a17fbbc73559
Revises: 
Create Date: 2026-09-13 20:35:27.792722
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a17fbbc73559'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('subniche', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commands_status'), ['status'], unique=False)

    op.create_table('sounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_asset_id', sa.String(length=128), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('local_path', sa.String(length=512), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_asset_id')
    )
    with op.batch_alter_table('sounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sounds_category'), ['category'], unique=False)

    op.create_table('visuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('missing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visuals_checksum'), ['checksum'], unique=False)

    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sound_id', sa.Integer(), nullable=False),
    sa.Column('license_type', sa.Enum('CC0', 'CC_BY_3', 'CC_BY_4', 'OWN', 'PROCEDURAL', 'AI_COMMERCIAL', name='license_type', native_enum=False, length=32), nullable=False),
    sa.Column('license_url', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('terms_snapshot_path', sa.String(length=512), nullable=True),
    sa.Column('provenance_notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=16), nullable=False),
    sa.Column('blacklisted', sa.Boolean(), nullable=False),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sound_id'], ['sounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sound_id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambient_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ambient_id'], ['ambients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'checksum')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_slug'), ['slug'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('PLANNED', 'RESEARCHING', 'AUDIO_SOURCE_SELECTION', 'AUDIO_GENERATION', 'AUDIO_MIXING', 'VISUAL_SELECTION', 'VIDEO_PROCESSING', 'RENDERING', 'QUALITY_CHECK', 'READY', 'UPLOADING', 'SCHEDULED', 'PUBLISHED', 'FAILED', name='video_state', native_enum=False, length=32), nullable=False),
    sa.Column('failed_from_state', sa.Enum('PLANNED', 'RESEARCHING', 'AUDIO_SOURCE_SELECTION', 'AUDIO_GENERATION', 'AUDIO_MIXING', 'VISUAL_SELECTION', 'VIDEO_PROCESSING', 'RENDERING', 'QUALITY_CHECK', 'READY', 'UPLOADING', 'SCHEDULED', 'PUBLISHED', 'FAILED', name='video_state', native_enum=False, length=32), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('target_publish_date', sa.Date(), nullable=True),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('combination_hash', sa.String(length=64), nullable=True),
    sa.Column('concept_fingerprint', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('output_path', sa.String(length=512), nullable=True),
    sa.Column('stage_timings', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('combination_hash')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_target_publish_date'), ['target_publish_date'], unique=False)

    op.create_table('api_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_costs_video_id'), ['video_id'], unique=False)

    op.create_table('descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('localizations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_descriptions_video_id'), ['video_id'], unique=False)

    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_errors_video_id'), ['video_id'], unique=False)

    op.create_table('publish_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('ambient_slug', sa.String(length=64), nullable=False),
    sa.Column('subniche', sa.String(length=32), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('stats_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publish_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_history_ambient_slug'), ['ambient_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_history_published_on'), ['published_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_history_video_id'), ['video_id'], unique=False)

    op.create_table('quota_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('bucket', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('quota_day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quota_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quota_usage_bucket'), ['bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_quota_usage_quota_day'), ['quota_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_quota_usage_video_id'), ['video_id'], unique=False)

    op.create_table('research_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('ambient_slug', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('term', sa.String(length=256), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_results_ambient_slug'), ['ambient_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_results_video_id'), ['video_id'], unique=False)

    op.create_table('states_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('from_state', sa.Enum('PLANNED', 'RESEARCHING', 'AUDIO_SOURCE_SELECTION', 'AUDIO_GENERATION', 'AUDIO_MIXING', 'VISUAL_SELECTION', 'VIDEO_PROCESSING', 'RENDERING', 'QUALITY_CHECK', 'READY', 'UPLOADING', 'SCHEDULED', 'PUBLISHED', 'FAILED', name='video_state', native_enum=False, length=32), nullable=True),
    sa.Column('to_state', sa.Enum('PLANNED', 'RESEARCHING', 'AUDIO_SOURCE_SELECTION', 'AUDIO_GENERATION', 'AUDIO_MIXING', 'VISUAL_SELECTION', 'VIDEO_PROCESSING', 'RENDERING', 'QUALITY_CHECK', 'READY', 'UPLOADING', 'SCHEDULED', 'PUBLISHED', 'FAILED', name='video_state', native_enum=False, length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('states_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_states_log_video_id'), ['video_id'], unique=False)

    op.create_table('thumbnails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('source_visual_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_visual_id'], ['visuals.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thumbnails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thumbnails_video_id'), ['video_id'], unique=False)

    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titles_video_id'), ['video_id'], unique=False)

    op.create_table('video_sounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('sound_id', sa.Integer(), nullable=False),
    sa.Column('layer', sa.String(length=64), nullable=False),
    sa.Column('seconds_used', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sound_id'], ['sounds.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_sounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_sounds_sound_id'), ['sound_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_sounds_video_id'), ['video_id'], unique=False)

    op.create_table('video_visuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('visual_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.ForeignKeyConstraint(['visual_id'], ['visuals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_visuals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_visuals_video_id'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_visuals_visual_id'), ['visual_id'], unique=False)

    op.create_table('youtube_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('privacy_status', sa.String(length=16), nullable=True),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('youtube_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_youtube_results_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtube_results_video_id'))

    op.drop_table('youtube_results')
    with op.batch_alter_table('video_visuals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_visuals_visual_id'))
        batch_op.drop_index(batch_op.f('ix_video_visuals_video_id'))

    op.drop_table('video_visuals')
    with op.batch_alter_table('video_sounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_sounds_video_id'))
        batch_op.drop_index(batch_op.f('ix_video_sounds_sound_id'))

    op.drop_table('video_sounds')
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titles_video_id'))

    op.drop_table('titles')
    with op.batch_alter_table('thumbnails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thumbnails_video_id'))

    op.drop_table('thumbnails')
    with op.batch_alter_table('states_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_states_log_video_id'))

    op.drop_table('states_log')
    with op.batch_alter_table('research_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_results_video_id'))
        batch_op.drop_index(batch_op.f('ix_research_results_ambient_slug'))

    op.drop_table('research_results')
    with op.batch_alter_table('quota_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quota_usage_video_id'))
        batch_op.drop_index(batch_op.f('ix_quota_usage_quota_day'))
        batch_op.drop_index(batch_op.f('ix_quota_usage_bucket'))

    op.drop_table('quota_usage')
    with op.batch_alter_table('publish_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_history_video_id'))
        batch_op.drop_index(batch_op.f('ix_publish_history_published_on'))
        batch_op.drop_index(batch_op.f('ix_publish_history_ambient_slug'))

    op.drop_table('publish_history')
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_errors_video_id'))

    op.drop_table('errors')
    with op.batch_alter_table('descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_descriptions_video_id'))

    op.drop_table('descriptions')
    with op.batch_alter_table('api_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_costs_video_id'))

    op.drop_table('api_costs')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_target_publish_date'))
        batch_op.drop_index(batch_op.f('ix_videos_state'))

    op.drop_table('videos')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_slug'))

    op.drop_table('recipes')
    op.drop_table('licenses')
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visuals_checksum'))

    op.drop_table('visuals')
    with op.batch_alter_table('sounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sounds_category'))

    op.drop_table('sounds')
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commands_status'))

    op.drop_table('commands')
    op.drop_table('ambients')
    # ### end Alembic commands ###
