"""Prints the compliance artifacts Ambient Bot writes for every video (used in the audit screencast)."""

from __future__ import annotations

import json
from pathlib import Path


def ascii_only(value: object) -> str:
    """The demo console is not UTF-8, so keep printed values plain ASCII."""
    return str(value).replace("±", "+/-").encode("ascii", "replace").decode("ascii")


def newest_complete_run() -> Path | None:
    runs = [p for p in sorted(Path("output/audio_runs").glob("*")) if (p / "licenses.json").exists()]
    return runs[-1] if runs else None


def main() -> None:
    run = newest_complete_run()
    if run is None:
        print("no run found")
        return
    print(f"Artifacts of one produced video: {run}\n")

    licenses = json.loads((run / "licenses.json").read_text(encoding="utf-8"))
    print("licenses.json  - every audio source used, with its license")
    print(f"  allowed licenses : {', '.join(licenses['allowed_licenses'])}")
    print(f"  all valid        : {licenses['all_valid']}")
    for entry in licenses["resources"]:
        origin = entry["source_url"] or "generated by the tool"
        print(f"  - {entry['item']:<22} {entry['license_type']:<12} {origin}")

    report = json.loads((run / "quality_report.json").read_text(encoding="utf-8"))
    print("\nquality_report.json  - gate that must pass before anything is uploaded")
    print(f"  passed: {report['passed']}")
    for check in report["checks"]:
        print(f"  - {check['name']:<22} {'OK  ' if check['passed'] else 'FAIL'} value={ascii_only(check['value'])} limit={ascii_only(check['threshold'])}")

    print("\nVideo footage is filmed by the channel owner; audio is generated by the tool or CC0 with a logged license.")


if __name__ == "__main__":
    main()
